### PR TITLE
check len of emparts before processing

### LINKED ISSUE #70: Neuerdings Fehlermeldung
Ich benutze SMA-EM schon eine ganze Zeit (in einem Docker Container). Neuerdings bekomme ich eine Fehlermeldung, auch nach einer kompletter Neuinstallation, wenn ich /opt/smaemd/sma-em-measurement.py mache:

```
unknown datatype: measurement 9217 datatype unknown raw_type 43
unknown datatype: measurement 0 datatype unknown raw_type 0
unknown datatype: measurement 65023 datatype unknown raw_type 7
unknown datatype: measurement 0 datatype unknown raw_type 93
unknown datatype: measurement 0 datatype unknown raw_type 0


SMA-EM Serial:2013313958
----sum----
Traceback (most recent call last):
  File "./sma-em-measurement.py", line 84, in <module>
    print ('P: consume:{}W {}kWh supply:{}W {}kWh'.format(emparts['pconsume'],emparts['pconsumecounter'],emparts['psupply'],emparts['psupplycounter']))
KeyError: 'pconsume'
```

Die Serial ist nicht die, die ich in der config eingetragen habe. Ich habe die config komplett aus dem Repository übernommen und nur die korrekte Serial eingefügt.

Eine ähnliche Fehlermeldung kommt nach /opt/smaemd/sma-em-capture-package.py:

```
unknown datatype: measurement 9217 datatype unknown raw_type 43
unknown datatype: measurement 0 datatype unknown raw_type 0
unknown datatype: measurement 65023 datatype unknown raw_type 7
unknown datatype: measurement 0 datatype unknown raw_type 209
unknown datatype: measurement 0 datatype unknown raw_type 0
----raw-output---
b'SMA\x00\x00\x04\x02\xa0\x00\x00\x00\x01\x00.\x00\x10`e\x0b\xd0x\x00\xbb\xa6\xa8\xc0\x00\x01$\x01+\xe03r\x00\x01\x00\x00\x00\x00\xdc\x80\r\x04\xfd\xff\x07\x00\x00\x00\x84\x03\x00\x00\xd162b\x00\x00\x00\x00\x00\x00\x00\x00'
----asci-output---
b'534d4100000402a000000001002e001060650bd07800bba6a8c0000124012be03372000100000000dc800d04fdff0700000084030000d13632620000000000000000'
----all-found-values---
serial: value:2013313958

```

### PR DESCRIPTION
**Pull request by mslacken**
close #70

### CODE REVIEW

**Comment by littleyoda** [comment]
I would suggest parsing the protocol id and then pick only packages with measured values

see my PR for SMA-EM https://github.com/kellerza/hassio-sma-em/pull/28

**Comment by mslacken** [comment]
As `sma-em-measurements.py` is just used for a quick check for what is going on in the network, it makes no difference how I ignore the stuff going  on in the network.

**Comment by littleyoda** [comment]
At this point I would like to disagree. These types of scripts are often taken as a basis by other people. And so it would be good if a good solution were used directly and not a quick hack.

Let's see what the maintainer's opinion is.

**Comment by dervomsee** [comment]
@datenschuft Is the project still maintained? For me this commit fixes the issue.

**Comment by datenschuft** [comment]
a robustness check has been added so this should no longer be necessary

**Pull request closed without merging**
