### PR TITLE
Framework enhancements and new features

### PR DESCRIPTION
**Pull request by Tommi2Day**
i made a few modifications to enhance this great tool to meke more configurable to allow developing und running on windows and add a new mqtt feature and a remote debug feature 
Each commits has a detailed explanations

### CODE REVIEW

**Comment by datenschuft** [comment]
thanks a lot
i will check your commits at the next days - happy holidays

**Comment by Tommi2Day** [comment]
i did some rework and added xtra plugins for extracting PV data from SMA Inverters via Modbus ,influxdb/grafana and for delivering data to IP-Symcon

**Comment by datenschuft** [comment]
Hi Thomas!
thank you for  your great work.
I'm running the development branch on my setups, because the daemon is running smoother in my setups without double forking and daemon handling. i let systemd handle this things.
the development branch is also a more object orientated coding style if features.
I would like to merge the dev-branch to the master brach. is it possible to rewrite the features to add them to the development branch? if not, i will ad your commits to the master branch and recode them someday to an object orientaded coding style.

**Comment by Tommi2Day** [comment]
Unfortunately, it looks i will not have the time to do the migration to dev dev branch within the next weeks. Acctually, it runs flawless with the master code.

**Comment by david-m-m** [comment]
@Tommi2Day: Wow. At first glance this is quite what I was thinking of, too. (Not sure though if I find the time to help porting this to the dev branch...)
@datenschuft: Maybe it's worth merging this into master nonetheless?

**Pull request merged**
