### PR TITLE
Datagram parser

### PR DESCRIPTION
**Pull request by david-m-m**
Hi @datenschuft,
as the datagram of the energy meters is well described I allowed myself to write a new datagram parser. It should be able to adapt in case the manufacturer chooses to add or remove values.
In any case the code has been running reliably for a couple of days now in my home.
I hope you find this a useful enhancement.
Greetings, david-m-m

### CODE REVIEW

**Comment by jhagberg** [comment]
Just for reference. This is how I wrote the parser from the SMA documents 
https://github.com/jhagberg/sma-em-influxdb/blob/c9df1660421be0ab3af35744864b04b85a8161a5/smaem2influxdb.py#L31-L39

**Comment by psilo909** [comment]
Bnb  S --  . .B vr  2Dr. Marc René FrießDipl.-Inf. (Univ.)  Herbststraße 30...v82223 EichenauTel.:   +49-8141-5262461mMobil:  +49-160-847548233 rE-Mail: rene.frie ss@gmx.deXing: https://www.xing.com/prm.mc.ofile/MarcRen Marcrene_friess 3 t e_Friess B4xThis message is for the designated recipient only and may contain privileged, proprietary, or otherwise private information. If you have received it in error, please notify the sender immmtediately and.m.ht delete the original. Any other use of the email by you is pwrohibited.
null

**Comment by david-m-m** [comment]
> Just for reference. This is how I wrote the parser from the SMA documents
> https://github.com/jhagberg/sma-em-influxdb/blob/c9df1660421be0ab3af35744864b04b85a8161a5/smaem2influxdb.py#L31-L39

@jhagberg: Thanks for the hint. Quite elegant and very compact. Nevertheless I (currently) refer my solution as it seems a bit more explicit for me and thus should help the reader in understanding.

**Comment by david-m-m** [comment]
First quick fix for new datagram.
Still missing: parse the new data correctly.

**Pull request merged**
